### PR TITLE
Update Place Albacete

### PR DESCRIPTION
**Pull request by jata84**
Updating `data/856/826/15/85682615.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by stepps00** [comment]
Hey @jata84 thanks for the update. Can you tell me what issue you're trying to solve with these name changes?

This record has both Spanish and English names, and it looks like the changes you're requesting update the English names to be Spanish. The record looks correct as-is to me, but interested in learning the use case here before this gets closed/merged.

**Comment by jata84** [comment]
Hi @stepps00. I have created an issue related to this pull request. Sorry for not creating the issue in the first place, but the pull request was created automatically via the web form.

This is the issue related to this pull request. 
https://github.com/whosonfirst-data/whosonfirst-data-admin-es/issues/40#issue-2231906289

**Comment by stepps00** [comment]
Ah - no problem. I understand the issue now, thanks for the detailed explanation in the issue.

I agree that there is a data discrepancy in Spain - it looks like there are naming issues with at least two regions. I need to dig around a bit more to understand the full extent of the issue, but my suspicion is that more than a single record needs to be updated.

Because Who's On First has stable identifiers and the idea of "superseding" records, rather than update this record's name(s), we'll likely want to deprecate this record entirely and supersede it into a completely new record. And because a new record will be created, descendant records will need to "know" about their new parent region via updates to their `wof:hierarchy` properties.. which is a long way of saying I'll likely close this change and the issue out, then file a new broader issue in the main [whosonfirst-data](https://github.com/whosonfirst-data/whosonfirst-data/issues) repo so others can chime in.

This also means that this change will unfortunately not be accepted as-is, but I'll loop you into any future changes to these region records (hopefully soon).

**Comment by stepps00** [comment]
Closing this PR in preference of https://github.com/whosonfirst-data/whosonfirst-data-admin-es/pull/41, though the commit in this PR was ported over.

**Pull request closed without merging**
